services:
  api:
    image: ghcr.io/skicomltd/ski-shop-backend:${IMAGE_TAG}
    container_name: skicom-shop-${NODE_ENV}
    restart: always
    env_file:
      - .env
    volumes:
      - ./firebase-admin.json:/app/firebase-admin.json:ro
    ports:
      - "${HOST_PORT}:${PORT}"
    depends_on:
      - postgres
      - redis

  migrate:
    image: ghcr.io/skicomltd/ski-shop-backend:${IMAGE_TAG}
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "
      if [ \"$NODE_ENV\" = \"development\" ]; then
        npm run migration:dev:reset;
      else
        npm run migration:run;
      fi
      "

  postgres:
    image: postgres:16-alpine
    container_name: postgres-${NODE_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_${NODE_ENV}:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-${NODE_ENV}
    restart: always

volumes:
  postgres_data_development:
  postgres_data_staging:
  postgres_data_production:
